name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deps:
    uses: ./.github/workflows/build.yml
  build:
    runs-on: ubuntu-latest
    needs:
      - build-deps
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Build App (Release)
      uses: ./.github/actions/gradle
      with:
        buildType: Release
        runTests: false
        keystore: ${{ secrets.RELEASE_KEYSTORE }}
        keystorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}

    - uses: actions/upload-artifact@v4
      with:
        name: ziti-mobile-edge-release.aab
        path: app/build/outputs/bundle/release/*.aab

    - uses: actions/upload-artifact@v4
      with:
        name: ziti-mobile-edge-release.apk
        path: app/build/outputs/apk/release/*.apk
