name: Android CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deps:
    uses: ./.github/workflows/build-dependencies.yml
  build:
    env:
      BUILD_TYPE: ${{ secret.RELEASE_KEYSTORE == '' && 'Debug' || 'Release' }}
    runs-on: ubuntu-latest
    needs:
      - build-deps
    steps:
    - run: env
    - uses: actions/checkout@v4
      with:
        fetch-depth: '0'

    - name: Build App (${{ env.BUILD_TYPE }})
      uses: ./.github/actions/gradle
      with:
        buildType: ${{ env.BUILD_TYPE }}
        runTests: false
        keystore: ${{ secrets.RELEASE_KEYSTORE }}
        keystorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}

    - uses: actions/upload-artifact@v4
      with:
        name: ziti-mobile-edge-${{ env.BUILD_TYPE }}.aab
        path: app/build/outputs/bundle/${{ env.BUILD_TYPE }}/*.aab

    - uses: actions/upload-artifact@v4
      with:
        name: ziti-mobile-edge-${{ env.BUILD_TYPE }}.apk
        path: app/build/outputs/apk/*/*.apk
