name: CI build

on:
  workflow_dispatch:

jobs:
  build-deps:

    runs-on: ubuntu-latest
    name: build dependencies[${{ matrix.target }}]
    strategy:
      matrix:
        target:
          - arm-android
          - arm64-android
          - x64-android
          - x86-android
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Cache ${{ matrix.target }} deps
        id: cache
        uses: actions/cache@v4
        with:
          path: tunnel/build/cmake/${{ matrix.target }}
          key: dependencies-${{ matrix.target }}-${{ hashFiles('./tunnel/vcpkg.json') }}

      - name: build if no cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: ./.github/actions/dependencies
        with:
          target: ${{ matrix.target }}

  build:
    runs-on: ubuntu-latest
    needs:
      - build-deps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: actions/cache/restore@v4
        with:
          path: tunnel/build/cmake/arm64-android
          key: dependencies-arm64-android-${{ hashFiles('./tunnel/vcpkg.json') }}
          fail-on-cache-miss: true
      - uses: actions/cache/restore@v4
        with:
          path: tunnel/build/cmake/arm-android
          key: dependencies-arm-android-${{ hashFiles('./tunnel/vcpkg.json') }}
          fail-on-cache-miss: true
      - uses: actions/cache/restore@v4
        with:
          path: tunnel/build/cmake/x64-android
          key: dependencies-x64-android-${{ hashFiles('./tunnel/vcpkg.json') }}
          fail-on-cache-miss: true
      - uses: actions/cache/restore@v4
        with:
          path: tunnel/build/cmake/x86-android
          key: dependencies-x86-android-${{ hashFiles('./tunnel/vcpkg.json') }}
          fail-on-cache-miss: true

      - uses: lukka/get-cmake@v3.30.1
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: run build
        run: |
          ./gradlew -PskipDependentBuild build

