name: build and cache native dependencies

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-deps:
    runs-on: ubuntu-latest
    name: build dependencies[${{ matrix.target }}]
    strategy:
      matrix:
        target:
          - arm-android
          - arm64-android
          - x64-android
          - x86-android
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Cache ${{ matrix.target }} deps
        id: cache
        uses: actions/cache@v4
        with:
          path: tunnel/build/cmake/${{ matrix.target }}
          key: dependencies-${{ matrix.target }}-${{ hashFiles('./tunnel/vcpkg.json') }}

      - name: build if no cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: ./.github/actions/dependencies
        with:
          target: ${{ matrix.target }}
