name: CI build

on:
  workflow_dispatch:

jobs:
  build-deps:

    runs-on: ubuntu-latest
    name: build dependencies[${{ matrix.target }}]
    strategy:
      matrix:
        target:
          - arm-android
          - arm64-android
          - x64-android
          - x86-android
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: Cache ${{ matrix.target }} deps
        id: cache
        uses: actions/cache@v4
        with:
          path: tunnel/build/cmake/${{ matrix.target }}
          key: ${{ matrix.target }}-${{ hashFiles('./tunnel/vcpkg.json') }}

      - name: build if no cache
        if: steps.cache.outputs.cache-hit != 'true'
        uses: ./.github/actions/dependencies
        with:
          target: ${{ matrix.target }}

  build:
    runs-on: ubuntu-latest
    needs:
      - build-deps
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - uses: lukka/get-cmake@v3.30.1
      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: gradle
      - name: run build
        run: |
          ./gradlew -PskipDependentBuild build

