name: Publish Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build App
        uses: ./.github/actions/gradle
        with:
          buildType: Release
          keystore: ${{ secrets.RELEASE_KEYSTORE }}
          keystorePassword: ${{ secrets.RELEASE_KEYSTORE_PASSWORD }}

      - name: Upload Release artifacts
        uses: softprops/action-gh-release@v2
        with:
          fail_on_unmatched_files: true
          files: |
            app/build/outputs/bundle/release/*.aab
            app/build/outputs/apk/release/*.apk
